# Generated by Django 5.0.6 on 2024-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="second_name",
            field=models.CharField(
                blank=True,
                help_text="Напишите Вашу фамилию",
                max_length=50,
                null=True,
                verbose_name="Фамилия",
            ),
        ),
    ]
