# Generated by Django 5.0.6 on 2024-07-13 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_networkobject_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networkobject",
            name="products",
        ),
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="network.networkobject",
                verbose_name="Поставщик",
            ),
        ),
    ]
