# Generated by Django 5.0.6 on 2024-07-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_networkobject_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkobject",
            name="products",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="network.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="network.networkobject",
                verbose_name="Поставщик",
            ),
        ),
    ]
