# Generated by Django 5.0.6 on 2024-07-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_remove_networkobject_products_alter_product_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkobject",
            name="time_of_creation",
            field=models.DateField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
