# Generated by Django 5.0.6 on 2024-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_alter_networkobject_time_of_creation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="provider",
        ),
        migrations.AddField(
            model_name="networkobject",
            name="products",
            field=models.ManyToManyField(blank=True, null=True, to="network.product"),
        ),
    ]
