# Generated by Django 5.0.6 on 2024-07-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_remove_product_provider_networkobject_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networkobject",
            options={
                "ordering": ["town"],
                "verbose_name": "Объект сети",
                "verbose_name_plural": "Объекты сети",
            },
        ),
    ]
