# Generated by Django 5.0.6 on 2024-07-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0015_alter_networkobject_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkobject",
            name="products",
            field=models.ManyToManyField(blank=True, to="network.product"),
        ),
    ]
